#version: "3"
services:
  gpt_agent:
    image: indycoagent
    container_name: indyco_agent
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./resources/input/prompts/:/llm4bi/resources/input/prompts/
      - ./resources/questions/:/llm4bi/resources/questions
    command:
      - /bin/bash
      - -c
      - |
        python3 src/test/testGPTAgent.py
        tail -f /dev/null