#version: "3"
services:
  gpt_agent:
    image: indycoagent
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BASE_PATH=/llm4bi
      - ITERATIONS=5
    volumes:
      - ./resources/input/prompts/indyco_tutorial_prompt.txt:/home/resources/input/prompts/indyco_tutorial_prompt.txt
      - ./resources/questions/questions.yaml:/home/resources/questions/questions.yaml
    command: 
      - /bin/bash
      - -c
      - |
        python3 src/test/testGPTAgent.py
        tail -f /dev/null